Feat : 네이버 지도 API
mini-moment/mimo-android pull request #13
Opened 2024-04-24 14:12 UTC by ho-taek

# 규칙
- [ ] Self Merge 금지!!
- [ ] 리뷰어들은 코드 자세히 읽고, 코멘트 남기기
- [ ] 라벨 활용해서 표시하기

## 관련 이슈
- #8 

## 작업 내용
![KakaoTalk_Photo_2024-04-24-23-08-02](https://github.com/Hustle-lab/hustleAOS/assets/71322949/3c06e2cb-8002-442d-b362-cafe99ff2bd3)

- 네이버 지도 API 기초 세팅을 했습니다!
- 위치 관련 권한 설정 코드 util에 넣었습니다.
- 지도 불러오는 것과 현재 위치 불러오는 것 까지 코드 작성했습니다!

## 리뷰어에게 하고 싶은 말
- 네이버 지도를 Fragment를 새로 만들지 않고 MapView를 쓰느라 생명주기를 일일이 다 적어줘야 했는데 이거 Map관련 Fragment 클래스를 만들어서 상속받을지. 아니면 childFragment 파서 적용할지 코드 짜면서 고민해 봐야 할 것 같습니다. 일단 이렇게 냅두고 작업 진행할게요!
  
## 참고 자료
- [네이버 문서](https://navermaps.github.io/android-map-sdk/guide-ko/4-2.html)

2024-04-24 15:08 UTC, jaehan4707 requested changes

2024-04-24 15:08 UTC, jaehan4707 commented on app/src/main/java/com/mimo/android/presentation/map/MapFragment.kt
>      }
해당 내용이 BaseFragment에 있으니 BaseFragement에서 binding객체를 만들고 해야할 작업을 abstract로 만들고 그걸 구현하면 코드가 더 괜찮을거 같은에 어떻게 생각하세용

2024-04-24 15:08 UTC, jaehan4707 commented on app/src/main/java/com/mimo/android/presentation/map/MapFragment.kt
> +                        LatLng(location.latitude, location.longitude)
여기도 저희 컨벤션에 맞게 
``` kotlin
val loc = if(location==null){

} else {
}
```
이렇게 바꾸는게 좋을거같아요

2024-04-24 15:08 UTC, jaehan4707 commented on app/src/main/java/com/mimo/android/presentation/map/MapFragment.kt
>      }
아 BaseFragment 상속을 안하고 있구나 죄송합니다

2024-04-24 23:54 UTC, ho-taek commented on app/src/main/java/com/mimo/android/presentation/map/MapFragment.kt
>      }
이거 따로 Map 전용으로 만들던가 해서 구현하고 싶은것만 넣으면 될 것 같기도 하고...? 그게 더 깔끔해지겠지?

2024-04-24 23:55 UTC, ho-taek commented on app/src/main/java/com/mimo/android/presentation/map/MapFragment.kt
> +                        LatLng(location.latitude, location.longitude)
넵! 수정하겠습니다

2024-04-25 04:15 UTC, pooya98 approved these changes
LGTM입니다 :)

2024-04-25 15:00 UTC, jaehan4707 approved these changes

2024-04-25 15:01 UTC, merged