signUpAPI 구현
mini-moment/mimo-android pull request #19
Opened 2024-04-28 12:32 UTC by jaehan4707

## 관련 이슈
- #18 

## 작업 내용

### 유저 정보 저장하기
<img width="663" alt="image" src="https://github.com/mini-moment/mimo-android/assets/99114456/be9d61cc-add3-43ed-8377-a57138d01196">

- 최초 로그인 시 유저 정보를 저장하는 signUpAPI 구현을 했습니다. 로컬 서버로 돌려본 결과 동작 이상 없었습니다.
- 에러 처리는 서버 로직에 따라 달라질것 같아서 아직 고민중입니다.

2024-04-30 02:31 UTC, ho-taek requested changes
고생하셨습니다!!
일단 Request change로 해놓을게!! 의견 맞추고 Approve로 바꾸면 될듯

2024-04-30 02:31 UTC, ho-taek commented on app/src/main/java/com/mimo/android/data/network/api/LoginApi.kt
> +    ): Response<Boolean>
Response Boolean으로 그냥 받는 것보다 상태 코드랑, data랑 묶어서 받는게 좋아보일 것 같은데 이거 한번 나도 네트워크 코드 짜면서 찾아볼게

2024-04-30 02:31 UTC, ho-taek commented on app/src/main/java/com/mimo/android/data/repositoryimpl/UserRepositoryImpl.kt
> +    }
이거 저번에 우리 얘기했던 것처럼 Repository에서 api 직접 주입 받지 말고, RemoteDataSource로 따로 빼서 주입 받는건 어떤 것 같아??

2024-04-30 07:55 UTC, jaehan4707 commented on app/src/main/java/com/mimo/android/data/network/api/LoginApi.kt
> +    ): Response<Boolean>
저도 만들어놓은 ApiResponse를 사용하면 좋을것같은데 
서버 반환 타입을 어떻게 내려줘야 할지 모르겠더라고용 저도 한번 알아볼게여

2024-04-30 07:59 UTC, jaehan4707 commented on app/src/main/java/com/mimo/android/data/repositoryimpl/UserRepositoryImpl.kt
> +    }
좋은것같아요 공부해보고 적용해볼게용

2024-05-01 03:43 UTC, pooya98 approved these changes
고생하셨습니다

2024-05-01 13:02 UTC, ho-taek approved these changes

2024-05-01 13:02 UTC, ho-taek commented on app/src/main/java/com/mimo/android/core/di/ApiModule.kt
> +    ): UserApi = retrofit.create()
retrofit.create(UserApi::class.java) 이런식으로 안 쳐도 
저 UserApi::class.java 코드 자체도 주입시켜주는거야??

2024-05-01 13:02 UTC, ho-taek commented on app/src/main/java/com/mimo/android/data/model/response/LoginResponse.kt
> +    val refreshToken: String? = null,
NetworkModuel 수정하면 얘도 domain으로 빼서 쓰는 것도 나쁘지 않을 것 같아!! 이렇게 하면 UI 레이어에서 data 레이어를 의존하게 되는거니까?

2024-05-01 13:03 UTC, ho-taek commented
위에꺼 확인해보고 머지해주십쇼!! 고생하셨슴다

2024-05-01 13:20 UTC, jaehan4707 commented on app/src/main/java/com/mimo/android/core/di/ApiModule.kt
> +    ): UserApi = retrofit.create()
![image](https://github.com/mini-moment/mimo-android/assets/99114456/8620f8fc-4e73-4645-8d57-46188b822319)

제가 알기론 create 함수 자체가 반환타입을 가지고 있어서 필요 없는것같아요

2024-05-01 13:22 UTC, jaehan4707 commented on app/src/main/java/com/mimo/android/data/model/response/LoginResponse.kt
> +    val refreshToken: String? = null,
그렇네요 LoginDao라던지 UI 딴에서 쓸 data를 만들긴 해야할것같아요
모듈 분리하면 그때 해도 괜찮을거 같은뎅 아닌가 ,,ㅎ

2024-05-01 13:29 UTC, merged