게시글 썸네일 추출 및 저장
mini-moment/mimo-android pull request #63
Opened 2024-06-16 08:12 UTC by jaehan4707

## 관련 이슈
- #60 

## 작업 내용
- 편집한 영상 업로드 성공 시 파일 삭제
- 편집한 영상 시작시간 기준으로 썸네일 추출
- 서버에 썸네일 전송

2024-06-16 08:40 UTC, ho-taek requested changes

2024-06-16 08:40 UTC, ho-taek commented on app/src/main/java/com/mimo/android/presentation/video/upload/UploadVideoFragment.kt
> +                            }
이 코드들 따로 util 확장함수로 빼서, RepositoryImpl에서 처리하도록 하면 나중에 다른데서 쓸때도 편할 것 같습니다!

2024-06-17 09:59 UTC, pooya98 approved these changes
엄청 고전하는 것 같던데.. 고생하셨어용

2024-06-19 11:49 UTC, ho-taek approved these changes

2024-06-19 11:49 UTC, merged