Feat/navigation bottomnav
mini-moment/mimo-android pull request #7
Opened 2024-04-22 14:35 UTC by ho-taek

# 규칙
- [ ] Self Merge 금지!!
- [ ] 리뷰어들은 코드 자세히 읽고, 코멘트 남기기
- [ ] 라벨 활용해서 표시하기

## 관련 이슈
- #6 MainActivity 및 bottomNavigation 세팅

## 작업 내용
- MainActivity에 MapFragment와 MyPageFragment를 바텀네비게이션을 통해 연결했습니다.!
- navigation 패키지 만들어서 main_navigation 세팅 했습니다.
- Timber 연결했습니다. -> Log.d보다 편함!(개인적 생각일지도)
- 각 뷰에 해당하는 패키지 만들었습니다!

## 리뷰어에게 하고 싶은 말
- navigation 코드가 맞는지 모르겠는데 혹시 수정할 부분이 있으면 말씀해주세요!
- 패키징 추가할거 넣고 했는데 data, domain 부분에는 어떻게 채워야할지 아직 안정한 것 같아서 이 부분 같이 정하면 좋을 것 같습니다!
- 다음 Hilt 추가해서 넣어놓을게요!
  
## 참고 자료

2024-04-22 14:51 UTC, jaehan4707 requested changes

2024-04-22 14:51 UTC, jaehan4707 commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
이거 지우셔도 될거같아용

2024-04-22 14:51 UTC, jaehan4707 commented on app/src/main/res/layout/fragment_map.xml
> +            android:text="@string/hello_blank_fragment" />
이것두!!

2024-04-22 14:51 UTC, jaehan4707 commented on app/src/main/java/com/mimo/android/presentation/map/MapFragment.kt
> +}
깃헙에선 마지막줄에 엔터 넣어주는게 컨벤션이더라고요
실제 코틀린 컨벤션도 맨마지막줄에 enterLine이 하나 들어가더라고용

2024-04-22 14:51 UTC, jaehan4707 commented on app/src/main/java/com/mimo/android/presentation/base/BaseActivity.kt
> +     val binding get() = _binding!!
음 private가 아닌 이유가 있을까여??
다른 view에서 다른 view의 binding 객체를 접근하는 일이 없을거 같아서 private로 막아두긴 했었어요

2024-04-22 14:55 UTC, ho-taek commented on app/src/main/java/com/mimo/android/presentation/map/MapFragment.kt
> +}
넵!

2024-04-22 14:55 UTC, ho-taek commented on app/src/main/res/layout/fragment_map.xml
> +            android:text="@string/hello_blank_fragment" />
넵!

2024-04-22 14:55 UTC, ho-taek commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
아차차 지울게요!

2024-04-22 14:55 UTC, ho-taek commented on app/src/main/java/com/mimo/android/presentation/base/BaseActivity.kt
> +     val binding get() = _binding!!
private로 쓰면 Fragment 딴에서 binding을 쓸 수가 있어???

2024-04-22 16:40 UTC, jaehan4707 commented on app/src/main/java/com/mimo/android/presentation/base/BaseActivity.kt
> +     val binding get() = _binding!!
아 생각해보니 당연히 접근이 안되는구나 죄송해용!

2024-04-23 11:05 UTC, jaehan4707 approved these changes

2024-04-23 12:04 UTC, pooya98 approved these changes
고생했소 짜이한

2024-04-23 12:05 UTC, merged