Refactor/build config
mini-moment/mimo-android pull request #83
Opened 2024-07-04 14:01 UTC by pooya98

## 관련 이슈
- #82 
- 
## 작업 내용

- mimo API 서버 URL에 대한 BuildConfig 변수 추가
- 하드코딩된 mimo API 서버 URL 수정

## 리뷰어에게 하고 싶은 말
- local.properties에 다음과 같이 각자의 로컬 IP를 설정하면 됩니다.
![image](https://github.com/mini-moment/mimo-android/assets/33233593/07936a07-1b56-43e2-a6ff-b68f84143502)

  `MIMO_SERVER_URL="http://{로컬 IP 주소}:8080/"`
  `MIMO_VIDEO_BASE_URL="http://{로컬 IP 주소}:8080/video/display/"`
  `MIMO_POST_THUMBNAIL_BASE_URL="http://{로컬 IP 주소}:8080/post/thumbnail/"`

2024-07-04 14:41 UTC, jaehan4707 requested changes

2024-07-04 14:41 UTC, jaehan4707 commented on app/build.gradle.kts
> +        buildConfigField("String", "MIMO_POST_THUMBNAIL_BASE_URL", "$mimoServerPostThumbnailUrlBase")
사진에서 local.properites의 각 값들이 동일한 url을 하드코딩하고있는데, 이렇게 한다면 위치가 바뀔경우 3개의 변수 값을 변화시켜야하는데 그것보다는  위에서 
```
val mimoServerVideoRulBase = mimoServerUrl + properties["MIMO_VIDEO_BASE_URL"] 
```
이런식으로 하면 어떨까요??

아마 local.properties에는 IP주소를 server_url에 저장하고, 나머지 세부 경로를 local.properties에 넣으면 편할것같아요

2024-07-05 00:29 UTC, ho-taek approved these changes
고생하셨습니다!

2024-07-05 13:19 UTC, jaehan4707 approved these changes

2024-07-05 13:19 UTC, merged